trigger:
- main

resources:
- repo: self

pool:
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    workspace:
      clean: all
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
- stage: DockerImageBuild
  displayName: DockerImageBuild
  dependsOn: Build
  jobs:
  - job: DockerImageBuild
    displayName: DockerImageBuild
    steps:
    - checkout: none
    - task: CmdLine@2
      inputs:
        script: |
          docker system prune -f --all
          docker build -t multicloudcontainer24registry.azurecr.io/samplewebapp:$(Build.BuildId) .
          trivy image --exit-code 0 --severity MEDIUM,HIGH multicloudcontainer24registry.azurecr.io/samplewebapp:$(Build.BuildId)
         #trivy image --exit-code 1 --severity CRITICAL multicloudcontainer24registry.azurecr.io/samplewebapp:$(Build.BuildId)
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerRegistryServiceConnection'
        repository: 'samplewebapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
- stage: KubernetesDeployment
  displayName: KubernetesDeployment
  dependsOn: DockerImageBuild
  jobs:
  - deployment: KubernetesDeployment
    environment: "dev"
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - task: CmdLine@2
            inputs:
              script: |
                helm repo add bitnami https://github.com/singhritesh85/helm-repo-for-ArgoCD/folo
                helm repo update
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'Azure DevOps Service Connection'
              azureResourceGroup: 'multicloud-rg'
              kubernetesCluster: 'multicloud-aks-cluster'
              namespace: 'three-tier-webapp'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: 'folo'
              releaseName: 'threetierwebapp'
              overrideValues: 'image.repository=multicloudcontainer24registry.azurecr.io/samplewebapp,image.tag=$(Build.BuildId),replicaCount=1,service.type=ClusterIP,service.port=80'
              recreate: true
              arguments: '--install --create-namespace'
