#JDBC Configutation for Database Connection
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://mysql-server.dexter-mysql3.private.mysql.database.azure.com:3306/accounts
jdbc.username=adminuser
jdbc.password=rn3LFSZ8RA00Vb5E

#Memcached Configuration For Active and StandBy Host
#For Active Host
memcached.active.host=10.104.0.3
memcached.active.port=11211
#For StandBy Host
memcached.standBy.host=10.104.0.4
memcached.standBy.port=11211

#RabbitMq Configuration
rabbitmq.address=10.20.0.100
rabbitmq.port=5672
rabbitmq.username=dexter
rabbitmq.password=Dexter321#!

